Repository LT-Students/DigitalOffice-UserService, pull requests merged in 2021-07, with the labels that each got.

#63 change class to record of DTO models
  src/UserService.Models.Dto/Configurations/CacheConfig.cs
  src/UserService.Models.Dto/Configurations/EmailEngineConfig.cs
  src/UserService.Models.Dto/Models/Certificates/CertificateInfo.cs
  src/UserService.Models.Dto/Models/Certificates/EditCertificate.cs
  src/UserService.Models.Dto/Models/CommunicationInfo.cs
  src/UserService.Models.Dto/Models/DepartmentInfo.cs
  src/UserService.Models.Dto/Models/EducationInfo.cs
  src/UserService.Models.Dto/Models/ImageInfo.cs
  src/UserService.Models.Dto/Models/PositionInfo.cs
  src/UserService.Models.Dto/Models/ProjectInfo.cs
  src/UserService.Models.Dto/Models/UserAchievementInfo.cs
  src/UserService.Models.Dto/Models/UserInfo.cs
  src/UserService.Models.Dto/Requests/Credentials/CreateCredentialsRequest.cs
  src/UserService.Models.Dto/Requests/Credentials/Filters/GetCredentialsFilter.cs
  src/UserService.Models.Dto/Responses/Credentials/CredentialsResponse.cs
  src/UserService.Models.Dto/Responses/OperationResultResponse.cs
  src/UserService.Models.Dto/Responses/User/UserResponse.cs
  src/UserService.Models.Dto/Responses/User/UsersResponse.cs
Labels: enhancement

#64 add create admin consumer
  Common.Configurations.targets
  src/UserService.Broker/Consumers/CreateAdminConsumer.cs
  src/UserService.Broker/UserService.Broker.csproj
  src/UserService.Business/Commands/User/GetUserCommand.cs
  src/UserService.Business/Helpers/Password/UserPasswordHash.cs
  src/UserService.Business/UserService.Business.csproj
  src/UserService.Data/Interfaces/IUserRepository.cs
  src/UserService.Data/UserRepository.cs
  src/UserService.Mappers/Db/DbUserMapper.cs
  src/UserService.Mappers/Db/Interfaces/IDbUserMapper.cs
  src/UserService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/UserService/Startup.cs
  src/UserService/appsettings.json
  test/UserService.Broker.UnitTests/Consumers/CreateAdminConsumerTests.cs
  test/UserService.Data.UnitTests/UserRepositoryTests.cs
  test/UserService.Mappers.UnitTests/DbUserMapperTests.cs
Labels: enhancement

#68 fix specification
  src/UserService/Startup.cs
Labels: bug

#67 edit create user
  Common.Configurations.targets
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Business/Commands/User/GetUserCommand.cs
  src/UserService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/UserService.Models.Dto/Requests/User/CreateUserRequest.cs
  src/UserService/Startup.cs
  src/UserService/appsettings.json
  test/UserService.Business.UnitTests/CreateUserCommandTests.cs
  test/UserService.Business.UnitTests/GetUserCommandTests.cs
Labels: enhancement

#69 add department and position to user of user find response
  Common.Configurations.targets
  src/UserService.Business/Commands/User/FindUserCommand.cs
  src/UserService.Data/Interfaces/IUserRepository.cs
  src/UserService.Data/UserRepository.cs
  src/UserService.Mappers/Models/Interfaces/IUserInfoMapper.cs
  src/UserService.Mappers/Models/UserInfoMapper.cs
  src/UserService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/UserService.Models.Dto/Models/UserInfo.cs
  src/UserService.Models.Dto/Requests/User/EditUserRequest.cs
  src/UserService.Validation/User/EditUserRequestValidator.cs
  src/UserService/appsettings.json
  test/UserService.Business.UnitTests/FindUserCommandTests.cs
  test/UserService.Mappers.UnitTests/Responses/UserResponseMapperTests.cs
Labels: enhancement

#74 added ref to kernel OperationResultResponse
  Common.Configurations.targets
  src/UserService.Business/Commands/Certificate/CreateCertificateCommand.cs
  src/UserService.Business/Commands/Certificate/EditCertificateCommand.cs
  src/UserService.Business/Commands/Certificate/Interfaces/ICreateCertificateCommand.cs
  src/UserService.Business/Commands/Certificate/Interfaces/IEditCertificateCommand.cs
  src/UserService.Business/Commands/Certificate/Interfaces/IRemoveCertificateCommand.cs
  src/UserService.Business/Commands/Certificate/RemoveCertificateCommand.cs
  src/UserService.Business/Commands/Education/CreateEducationCommand.cs
  src/UserService.Business/Commands/Education/EditEducationCommand.cs
  src/UserService.Business/Commands/Education/Interfaces/ICreateEducationCommand.cs
  src/UserService.Business/Commands/Education/Interfaces/IEditEducationCommand.cs
  src/UserService.Business/Commands/Education/Interfaces/IRemoveEducationCommand.cs
  src/UserService.Business/Commands/Education/RemoveEducationCommand.cs
  src/UserService.Business/Commands/Password/ChangePasswordCommand.cs
  src/UserService.Business/Commands/Password/ForgotPasswordCommand.cs
  src/UserService.Business/Commands/Password/Interfaces/IChangePasswordCommand.cs
  src/UserService.Business/Commands/Password/Interfaces/IForgotPasswordCommand.cs
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Business/Commands/User/DisableUserCommand.cs
  src/UserService.Business/Commands/User/EditUserCommand.cs
  src/UserService.Business/Commands/User/Interfaces/ICreateUserCommand.cs
  src/UserService.Business/Commands/User/Interfaces/IDisableUserCommand.cs
  src/UserService.Business/Commands/User/Interfaces/IEditUserCommand.cs
  src/UserService.Models.Dto/Enums/OperationResultStatusType.cs
  src/UserService.Models.Dto/Responses/OperationResultResponse.cs
  src/UserService/Controllers/CertificateController.cs
  src/UserService/Controllers/EducationController.cs
  src/UserService/Controllers/PasswordController.cs
  src/UserService/Controllers/UsersController.cs
  test/UserService.Business.UnitTests/CertificateCommandTests/CreateCertificateCommandTests.cs
  test/UserService.Business.UnitTests/CertificateCommandTests/EditCertificateCommandTests.cs
  test/UserService.Business.UnitTests/CertificateCommandTests/RemoveCertificateCommandTests.cs
  test/UserService.Business.UnitTests/EditUserCommandTests.cs
  test/UserService.Business.UnitTests/EducationsCommandTests/CreateEducationCommandTests.cs
  test/UserService.Business.UnitTests/EducationsCommandTests/EditEducationCommandTests.cs
  test/UserService.Business.UnitTests/EducationsCommandTests/RemoveEducationCommandTests.cs
  test/UserService.Business.UnitTests/ForgotPasswordCommandTests.cs
Labels: enhancement

#75 fix github actions
  .github/workflows/main.yml
Labels: documentation

#72 updated find user endpoint
  Common.Configurations.targets
  src/UserService.Business/Commands/User/FindUserCommand.cs
  src/UserService.Mappers/Models/DepartmentInfoMapper.cs
  src/UserService.Mappers/Models/ImageInfoMapper.cs
  src/UserService.Mappers/Models/Interfaces/IDepartmentInfoMapper.cs
  src/UserService.Mappers/Models/Interfaces/IImageInfoMapper.cs
  src/UserService.Mappers/Models/Interfaces/IOfficeInfoMapper.cs
  src/UserService.Mappers/Models/Interfaces/IPositionInfoMapper.cs
  src/UserService.Mappers/Models/Interfaces/IRoleInfoMapper.cs
  src/UserService.Mappers/Models/Interfaces/IUserInfoMapper.cs
  src/UserService.Mappers/Models/OfficeInfoMapper.cs
  src/UserService.Mappers/Models/PositionInfoMapper.cs
  src/UserService.Mappers/Models/RoleInfoMapper.cs
  src/UserService.Mappers/Models/UserInfoMapper.cs
  src/UserService.Mappers/Responses/UserResponseMapper.cs
  src/UserService.Models.Dto/Configurations/RabbitMqConfig.cs
  src/UserService.Models.Dto/Models/OfficeInfo.cs
  src/UserService.Models.Dto/Models/RoleInfo.cs
  src/UserService.Models.Dto/Models/UserInfo.cs
  src/UserService.Models.Dto/Responses/User/UserResponse.cs
  src/UserService.Validation/UserService.Validation.csproj
  src/UserService/appsettings.json
  test/UserService.Business.UnitTests/FindUserCommandTests.cs
  test/UserService.Business.UnitTests/GetUserCommandTests.cs
  test/UserService.Mappers.UnitTests/Responses/UserResponseMapperTests.cs
Labels: enhancement

#71 Add token life time
  Common.Configurations.targets
  src/UserService.Broker/Consumers/GetUsersDataConsumer.cs
  src/UserService.Business/Commands/Credentials/CreateCredentialsCommand.cs
  src/UserService.Models.Dto/Responses/Credentials/CredentialsResponse.cs
  test/UserService.Broker.UnitTests/Consumers/GetUsersDataConsumerTests.cs
  test/UserService.Business.UnitTests/CreateCredentialsCommandTests.cs
Labels: enhancement

#70 Add check in creating user
  src/UserService.Business/Commands/Credentials/CreateCredentialsCommand.cs
  src/UserService.Business/Commands/Credentials/Interfaces/ICreateCredentialsCommand.cs
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Data.Provider.MsSql.Ef/Migrations/20210708115900_AddUniqueConstraintToLoginAndCommunicationValue.cs
  src/UserService.Data/Interfaces/IUserCredentialsRepository.cs
  src/UserService.Data/Interfaces/IUserRepository.cs
  src/UserService.Data/UserCredentialsRepository.cs
  src/UserService.Data/UserRepository.cs
  src/UserService.Validation/User/Certificates/EditCertificateRequestValidator.cs
  src/UserService.Validation/User/Education/CreateEducationRequestValidator.cs
  src/UserService/Controllers/CredentialsController.cs
  src/UserService/Controllers/UsersController.cs
  test/UserService.Business.UnitTests/CreateCredentialsCommandTests.cs
  test/UserService.Data.UnitTests/UserCredentialsRepositoryTests.cs
  test/UserService.Data.UnitTests/UserRepositoryTests.cs
  test/UserService.Validation.UnitTests/Certificate/EditCertificateRequestValidatorTests.cs
  test/UserService.Validation.UnitTests/Education/CreateEducationRequestValidatorTests.cs
Labels: enhancement

#76 remove nameRegex from validators
  src/UserService.Validation/User/CreateUserRequestValidator.cs
  src/UserService.Validation/User/EditUserRequestValidator.cs
  test/UserService.Validation.UnitTests/EditUserRequestValidatorTests.cs
  test/UserService.Validation.UnitTests/UserValidatorTests.cs
Labels: bug

#78 update get and edit user
  src/UserService.Business/Commands/User/EditUserCommand.cs
  src/UserService.Business/Commands/User/GetUserCommand.cs
  src/UserService.Mappers/Models/PatchDbUserMapper.cs
  src/UserService.Mappers/Responses/Interfaces/IUserResponseMapper.cs
  src/UserService.Mappers/Responses/UserResponseMapper.cs
  src/UserService.Models.Dto/Requests/User/EditUserRequest.cs
  src/UserService.Models.Dto/Requests/User/Filters/GetUserFilter.cs
  src/UserService.Validation/User/EditUserRequestValidator.cs
  src/UserService/Startup.cs
  test/UserService.Business.UnitTests/EditUserCommandTests.cs
  test/UserService.Business.UnitTests/GetUserCommandTests.cs
  test/UserService.Mappers.UnitTests/Responses/UserResponseMapperTests.cs
Labels: enhancement

#77 Changed GetUsersDataConsumer
  src/UserService.Broker/Consumers/GetUsersDataConsumer.cs
  test/UserService.Broker.UnitTests/Consumers/GetUsersDataConsumerTests.cs
Labels: enhancement

#79 fix start working at in mapper
  src/UserService.Mappers/Models/PatchDbUserMapper.cs
  src/UserService.Mappers/Models/UserInfoMapper.cs
Labels: bug

#80 Update validation of optional string properties
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Business/Commands/User/EditUserCommand.cs
  src/UserService.Mappers/Db/DbUserMapper.cs
  src/UserService.Mappers/Models/PatchDbUserMapper.cs
Labels: bug

#82 Docs/change actions
  .github/workflows/main.yml
Labels: documentation

#83 Fix create user
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Validation/User/CreateUserRequestValidator.cs
  test/UserService.Validation.UnitTests/UserValidatorTests.cs
Labels: bug

#84 remove resender
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Business/Helpers/Email/EmailResender.cs
  src/UserService/Startup.cs
Labels: enhancement

#89 Feature/updated kernel and responses
  Common.Configurations.targets
  src/UserService.Mappers/Models/CertificateInfoMapper.cs
  src/UserService.Mappers/Models/EducationInfoMapper.cs
  src/UserService.Mappers/Models/UserInfoMapper.cs
  src/UserService.Mappers/Responses/UserResponseMapper.cs
  src/UserService.Models.Dto/Enums/CommunicationType.cs
  src/UserService.Models.Dto/Enums/EducationType.cs
  src/UserService.Models.Dto/Enums/FormEducation.cs
  src/UserService.Models.Dto/Enums/UserGender.cs
  src/UserService.Models.Dto/Enums/UserStatus.cs
  src/UserService.Models.Dto/Models/CertificateInfo.cs
  src/UserService.Models.Dto/Models/CommunicationInfo.cs
  src/UserService.Models.Dto/Models/EducationInfo.cs
  src/UserService.Models.Dto/Models/UserInfo.cs
  test/UserService.Business.UnitTests/FindUserCommandTests.cs
  test/UserService.Mappers.UnitTests/Models/EducationInfoMapperTests.cs
  test/UserService.Mappers.UnitTests/Responses/UserResponseMapperTests.cs
Labels: enhancement

#91 fix edit user
  src/UserService.Business/Commands/User/EditUserCommand.cs
Labels: bug

#90 Feature/fix logger in commands
  src/UserService.Business/Commands/Certificate/CreateCertificateCommand.cs
  src/UserService.Business/Commands/Certificate/EditCertificateCommand.cs
  src/UserService.Business/Commands/Certificate/RemoveCertificateCommand.cs
  src/UserService.Business/Commands/Communication/EditCommunicationCommand.cs
  src/UserService.Business/Commands/Credentials/CreateCredentialsCommand.cs
  src/UserService.Business/Commands/Password/ForgotPasswordCommand.cs
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Business/Commands/User/DisableUserCommand.cs
  src/UserService.Business/Commands/User/EditUserCommand.cs
  src/UserService.Business/Commands/User/FindUserCommand.cs
  src/UserService.Business/Commands/User/GetUserCommand.cs
  test/UserService.Business.UnitTests/FindUserCommandTests.cs
Labels: enhancement

#93 update get users data consumer
  Common.Configurations.targets
  src/UserService.Broker/Consumers/GetUsersDataConsumer.cs
  test/UserService.Broker.UnitTests/Consumers/GetUsersDataConsumerTests.cs
Labels: enhancement

#94 remove default admin data, fix editUser command
  src/UserService.Broker/Consumers/CreateAdminConsumer.cs
  src/UserService.Business/Commands/User/CreateUserCommand.cs
  src/UserService.Business/Commands/User/EditUserCommand.cs
  src/UserService.Business/Commands/User/FindUserCommand.cs
  src/UserService.Data.Provider.MsSql.Ef/InitialData/AdminCredentials.cs
  src/UserService.Data.Provider.MsSql.Ef/Migrations/20201011111059_ReworkDbModels.cs
  src/UserService.Data.Provider.MsSql.Ef/Migrations/20210329163012_UpdateAdminData.cs
  src/UserService.Data.Provider.MsSql.Ef/Migrations/20210331083200_AddAdminCommunications.cs
  src/UserService.Data.Provider.MsSql.Ef/Migrations/20210730012700_AddIsActiveToUserCredentials.cs
  src/UserService.Data/Interfaces/IUserCredentialsRepository.cs
  src/UserService.Data/Interfaces/IUserRepository.cs
  src/UserService.Data/UserCredentialsRepository.cs
  src/UserService.Data/UserRepository.cs
  src/UserService.Mappers/Db/DbUserCredentialsMapper.cs
  src/UserService.Models.Db/DbUserCredentials.cs
  test/UserService.Broker.UnitTests/Consumers/CreateAdminConsumerTests.cs
  test/UserService.Data.UnitTests/UserCredentialsRepositoryTests.cs
  test/UserService.Data.UnitTests/UserRepositoryTests.cs
Labels: bug
